'use client'

import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'
import { AlertTriangle, ShieldCheck, Heart } from 'lucide-react'

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      <main className="flex-1 mx-auto max-w-4xl px-4 sm:px-6 py-12 sm:py-16">
        <div className="space-y-10">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-amber-500/20 bg-amber-500/5 text-amber-500 text-xs font-mono font-medium mb-4">
              <AlertTriangle className="h-3.5 w-3.5" />
              LEGAL REGULATORY DISCLOSURES
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
              Disclaimer & Disclosures
            </h1>
            <p className="text-muted-foreground mt-2 text-sm">
              Last Updated: May 29, 2026
            </p>
          </div>

          <div className="prose prose-invert max-w-none space-y-6 text-sm sm:text-base leading-relaxed text-muted-foreground">
            <div className="p-5 rounded-xl border border-amber-500/30 bg-amber-500/5 text-amber-500/90 font-medium">
              Important: Please read this disclaimer carefully before using AllTimeTrader.com. By using this website, you agree to all terms outlined here.
            </div>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-foreground flex items-center gap-2">
                1. Not a SEBI Registered Entity
              </h2>
              <p>
                AllTimeTrader.com is <strong>NOT</strong> registered with the Securities and Exchange Board of India (SEBI) as an Investment Advisor, Research Analyst, Stock Broker, or Portfolio Manager. 
              </p>
              <p>
                The owner of this website is an individual trader and developer. All information, analyses, calculators, and opinions expressed on this site are solely for personal and educational research and do not represent professional financial or investment advisory.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-foreground">
                2. Educational Purpose Only
              </h2>
              <p>
                All tools, calculators, journals, worksheets, and assets hosted on AllTimeTrader.com are intended for **educational, mathematical demonstration, and discipline-tracking purposes only**. 
              </p>
              <p>
                Calculations generated by our tools (such as cost averaging, compound annual growth rate, position sizing, option pain, etc.) are based on standard mathematical formulas and user inputs. They do not constitute investment tips, trading signals, or buy/sell recommendations.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-foreground">
                3. Market Risks & Past Performance
              </h2>
              <p>
                Trading and investing in equities, derivatives (Futures &amp; Options), commodities, and currencies are subject to significant **market risk**. Leverage in F&amp;O trading can lead to losses that exceed your initial capital. 
              </p>
              <p>
                Past performance of any trading strategies, model portfolios, or historical data showcased on this site is not a guarantee of future returns. You are solely responsible for your own trading decisions.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-foreground">
                4. Data Accuracy and Delays
              </h2>
              <p>
                We source data from publicly available sources and APIs. While we make every effort to optimize our feeds and servers for accuracy, market data may be delayed, incomplete, or temporarily unavailable due to server lag or API downtimes. 
              </p>
              <p>
                You should always double-check prices, index levels, option chains, and calculations against official stock exchange feeds (NSE/BSE) or your registered broker terminal before committing real capital. We hold no liability for any trading losses caused by data discrepancies.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-foreground">
                5. Affiliate & Referral Disclosure
              </h2>
              <p>
                In compliance with marketing guidelines, we declare that AllTimeTrader.com participates in partner referral programs with leading SEBI-registered stockbrokers (such as Zerodha, Dhan, Upstox, etc.). 
              </p>
              <p>
                When you click on Demat opening banners or buttons on our site and successfully register an account, we may receive a referral commission. This commission helps maintain our servers, tools, and calculators completely free of charge for our users. We only recommend platforms we personally use and trust.
              </p>
            </section>
          </div>

          <div className="border-t border-border/50 pt-8 flex items-center gap-3 text-xs text-muted-foreground">
            <ShieldCheck className="h-5 w-5 text-emerald-500" />
            <span>Consult a certified financial planner or SEBI-registered advisor before executing any market trades.</span>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
